name       : glava
version    : 1.6.3
release    : 4
source     :
    - https://github.com/wacossusca34/glava/archive/v1.6.3.tar.gz : b90e39884b5e348734a86029b6a90db66b9fd63e72d21dec9cf3fa2d5447ac63
license    : GPL-3.0-only
component  : multimedia.audio
summary    : OpenGL audio spectrum visualizer
description: |
    GLava is an OpenGL audio spectrum visualizer.
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-shader-install-directory.patch
build      : |
    %make
install    : |
    %make_install
