name       : glava
version    : 1.5.8
release    : 1
source     :
    - https://github.com/wacossusca34/glava/archive/v1.5.8.tar.gz : 3dab12f87512f97c43a309da7aee5014c48a1cc7188949712c0665777f9a98d7
license    : GPL-3.0-only
component  : multimedia.audio
summary    : OpenGL audio spectrum visualizer
description: |
    GLava is an OpenGL audio spectrum visualizer.
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xext)
    - pkgconfig(xrender)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-shader-install-directory.patch
build      : |
    %make
install    : |
    %make_install
